<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Speaker;

class SpeakerSeeder extends Seeder
{
    public function run(): void
    {
        $speakers = [
            [
                'uuid' => Str::uuid(),
                'name' => 'Federico',
                'last_name' => 'De Arteaga Vidiella',
                'gmail' => 'federico.arteaga@example.com',
                'document_type_id' => 1,
                'document_number' => '100000001',
                'phone' => '0000000001',
                'bio' => 'Experto en innovación turística y sostenibilidad.',
                'specialization' => 'Innovación Turística',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Javier',
                'last_name' => 'Suescún',
                'gmail' => 'javier.suescun@example.com',
                'document_type_id' => 1,
                'document_number' => '100000002',
                'phone' => '0000000002',
                'bio' => 'Especialista en cocina tradicional y fotografía gastronómica.',
                'specialization' => 'Fotografía Gastronómica',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'María Cecilia',
                'last_name' => 'López',
                'gmail' => 'mariacecilia.lopez@example.com',
                'document_type_id' => 1,
                'document_number' => '100000003',
                'phone' => '0000000003',
                'bio' => 'Experta en neuroartesanía, sostenibilidad e innovación empresarial.',
                'specialization' => 'Neuroartesanía e Innovación',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => 'https://www.instagram.com/maria_cecilia_lopez',
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Andrés',
                'last_name' => 'Díaz Molina',
                'gmail' => 'andres.diaz@example.com',
                'document_type_id' => 1,
                'document_number' => '100000004',
                'phone' => '0000000004',
                'bio' => 'Especialista en soluciones digitales y gestión productiva.',
                'specialization' => 'Soluciones Digitales',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Jhon Faber',
                'last_name' => 'Giraldo',
                'gmail' => 'jhon.giraldo@example.com',
                'document_type_id' => 1,
                'document_number' => '100000005',
                'phone' => '0000000005',
                'bio' => 'Experto en marketing de destinos turísticos.',
                'specialization' => 'Marketing Turístico',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Lucas',
                'last_name' => 'López',
                'gmail' => 'lucas.lopez@example.com',
                'document_type_id' => 1,
                'document_number' => '100000006',
                'phone' => '0000000006',
                'bio' => 'Especialista en WayFinding y ciudades legibles.',
                'specialization' => 'Diseño Urbano',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Alberto',
                'last_name' => 'Mena',
                'gmail' => 'alberto.mena@example.com',
                'document_type_id' => 1,
                'document_number' => '100000007',
                'phone' => '0000000007',
                'bio' => 'Experto en inteligencia artificial aplicada al turismo y diseño.',
                'specialization' => 'Inteligencia Artificial',
                'photo_url' => null,
                'linkedin_url' => 'https://www.linkedin.com/in/alberto-mena',
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Juan Carlos',
                'last_name' => 'León',
                'gmail' => 'juan.leon@example.com',
                'document_type_id' => 1,
                'document_number' => '100000008',
                'phone' => '0000000008',
                'bio' => 'Diseñador de moda y creador de colecciones cápsula sostenibles.',
                'specialization' => 'Moda y Diseño',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Natalia',
                'last_name' => 'Bayona',
                'gmail' => 'natalia.bayona@example.com',
                'document_type_id' => 1,
                'document_number' => '100000009',
                'phone' => '0000000009',
                'bio' => 'Directora de ONU Turismo y referente global en estrategias comerciales.',
                'specialization' => 'Estrategias Turísticas Globales',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            // Puedes continuar así con los demás speakers como Wilfer Montoya, Julio Acosta, Lucía Risco, etc.
        ];

        foreach ($speakers as $speaker) {
            Speaker::create($speaker);
        }
    }
}
