<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Speaker;

class SpeakerSeeder extends Seeder
{
    public function run(): void
    {
        $speakers = [
            [
                'uuid' => Str::uuid(),
                'name' => 'Federico',
                'last_name' => 'De Arteaga Vidiella',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Experto con Doctorado (Ph.D.) en Innovación y Responsabilidad Social, MBA en Negocios Internacionales e Ingeniería Agrónoma. Su trayectoria profesional se destaca por su liderazgo como Presidente de la Red de Destinos Turísticos Inteligentes de Iberoamérica y su rol como consultor de alto nivel para el Banco Interamericano de Desarrollo (BID) en proyectos de gobernanza y sostenibilidad.
                        Posee una vasta experiencia en la implementación de metodologías de turismo inteligente, habiendo asesorado a entidades como la SECTUR en México y la Secretaría de Turismo de Cali en Colombia. Su experiencia se complementa con una sólida visión corporativa, forjada como director en Grupo JB (Mundo Cuervo).
                        Fue seleccionado por su perfil único que integra una rigurosa formación académica con experiencia probada en la creación y gobernanza de modelos sostenibles e innovadores en el sector público y privado a escala internacional.',
                'specialization' => 'Innovación y Responsabilidad Social',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Javier',
                'last_name' => 'Suescún',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Comunicador Social egresado de la Universidad de Pamplona y candidato a Magíster en Educación. Cuenta con una sólida trayectoria en el campo de la producción audiovisual y la fotografía, desempeñándose en diversos medios de comunicación y productoras de la región, donde ha participado en la realización de contenidos visuales con enfoque narrativo y documental.
                        Posee más de 10 años de experiencia como docente universitario en distintas instituciones académicas, en las cuales ha orientado asignaturas relacionadas con fotografía, televisión y medios audiovisuales. Su labor docente se caracteriza por integrar la teoría con la práctica profesional, promoviendo el desarrollo de competencias técnicas, creativas y críticas en los estudiantes, con una visión integral de la comunicación visual y su impacto en la sociedad.',
                'specialization' => 'Magíster en Educación',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'María Cecilia',
                'last_name' => 'López',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Magister en mercadeo, Profesional en Diseño de Modas y textiles. Con más de 27 años de experiencia en el sector. Nominada a lápiz de acero. Conferencista Nacional e Internacional avalada por la Universidad de Palermo (Argentina), el Instituto Autónomo del Ecuador, Universidad Autónoma de Xochimilco (México), la Universidad del Norte, Universidad Iberoamericana y Universidad Libre de la ciudad de Barranquilla Colombia.
                        Co autora de libros como "Connotaciones Socio-culturales en el Diseño de Modas”, El sentido de la moda, breve diccionario sobre el vestuario del Caribe” y Arte y Pectorales, un legado de las culturas ancestrales. En Resultados finales de la convocatoria 737 de fui categorizada como investigador asociado al grupo de investigación Ecodesarrollo.',
                'specialization' => 'Magister en mercadeo',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Andrés',
                'last_name' => 'Díaz Molina',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Ingeniero de Sistemas (Universidad de Pamplona), especialista en Seguridad de la Información (Uniandes) y en Derecho Informático (Externado). Se ha destacado por liderar estrategias de ciberseguridad en entidades como MinTIC, ICBF, SuperSalud y la Nueva EPS. Con más de 16 años de experiencia en el sector público, ha ocupado roles clave como asesor, coordinador y oficial de seguridad y privacidad de la información. Su perfil técnico, jurídico y estratégico lo convierte en un referente nacional en protección de activos digitales. Fue seleccionado por su liderazgo, visión integral y capacidad para fortalecer la seguridad tecnológica del Estado. Actualmente, dirige la Oficina de Tecnologías de la Información del Ministerio.',
                'specialization' => 'Seguridad de la Información y Derecho Informático',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Jhon Faber',
                'last_name' => 'Giraldo',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Comunicador social de profesión y un apasionado por el marketing, el turismo, la cultura y por supuesto el café.
                        Fotógrafo, estratega y creador de contenido audiovisual para sus redes y dentro del equipo de Marketing de su amado Parque Nacional del Café, en el que está vinculado hace 26 años y dentro del cual ha podido fortalecer su perfil profesional.',
                'specialization' => null,
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Lucas',
                'last_name' => 'López',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Diseñador de la Comunicación Gráfica con título otorgado por la Universidad Autónoma de Occidente (2012) y Magíster en Diseño y Creación Interactiva por la Universidad de Caldas (2015). Cuenta con una sólida trayectoria en diseño gráfico y comunicación visual, respaldada por su experiencia como Diseñador Senior en la firma Strohhaker (2010–2015), donde lideró proyectos orientados al desarrollo de soluciones visuales estratégicas.
                        Entre 2016 y 2022 se desempeñó como docente de cátedra en el programa de Diseño de la Comunicación Gráfica de la Universidad Autónoma de Occidente, aportando su conocimiento en áreas como diseño de información, interacción y visualización. Su enfoque académico se ha complementado con procesos investigativos, siendo autor de la publicación Ciudades legibles. Una mirada desde el diseño de información y su contribución para hacer mejores lugares (2020), editada por el Programa Editorial de la Universidad Autónoma de Occidente. Su perfil integra la práctica profesional con la reflexión crítica sobre el rol del diseño en la configuración de entornos más comprensibles y habitables.',
                'specialization' => 'Magíster en Diseño y Creación Interactiva',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Alberto',
                'last_name' => 'Mena',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Consultor estratégico, CEO y fundador de X-TRATEGIC, firma líder en El Salvador especializada en asesoría para el sector hotelero y turístico. Cuenta con más de 12 años de experiencia en turismo, destacándose en estrategia, gestión hotelera, marketing digital y liderazgo organizacional. Ha trabajado con éxito en sectores público y privado, liderando proyectos de inversión y transformación digital. Su enfoque combina tecnología, sostenibilidad e innovación en la experiencia del cliente. Ha asesorado múltiples organizaciones en la adopción de soluciones digitales y uso estratégico de la IA. Fue seleccionado por su visión integral y su capacidad para impulsar la competitividad del sector turístico con herramientas modernas y efectivas.',
                'specialization' => null,
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Juan Carlos',
                'last_name' => 'León',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Maestrante en Gestión de las Organizaciones, profesional en diseño de modas y alta costura (U A C), con estudios completos como tecnólogo en Diseño textil (U A C) técnico en producción industrial de confecciones (S E N A y estudios básicos en publicidad diseño publicitario (Corporación educativa del Litoral).',
                'specialization' => 'Maestrante en Gestión de las Organizaciones',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Natalia',
                'last_name' => 'Bayona',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Natalia Bayona fue una pionera en la administración pública que inició su carrera trabajando para el gobierno de su país natal, Colombia.
                        Durante su labor en ProColombia, la agencia gubernamental nacional dedicada a la promoción del turismo, encabezó la promoción del turismo de Colombia en el bloque comercial del MERCOSUR (Argentina, Brasil, Paraguay y Uruguay) y fue la primera directora de la oficina comercial del país para Argentina, Uruguay y Paraguay. En 2013, con solo 27 años, la Sra. Bayona se convirtió en la gestora más joven responsable de promover el turismo de su país en todo el mundo.',
                'specialization' => null,
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Wilfer',
                'last_name' => 'Montoya Benjumea',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Diseñador visual, editor y compositor VFX para cine y televisión con más de 11 años de experiencia en la industria creativa.  Tiene formación en publicidad y diseño, complementada con estudios avanzados en animación, que le ha permitido desarrollar un enfoque multidisciplinario para la creación de experiencias visuales de alto impacto.
                        Actualmente es un apasionado en el campo de la inteligencia artificial generativa, explorando herramientas avanzadas como ComfyUI, Stable Diffusion y MidJourney entre muchas otras para la generación de imagen, video y audio. Su enfoque es transformar ideas abstractas en experiencias visuales únicas, aprovechando el potencial de la IA en la industria del entretenimiento y la producción audiovisual.',
                'specialization' => 'Estudios avanzados en animación',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Otniel Josafat',
                'last_name' => 'López Altamirano',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Doctor en Diseño de Producto (UNESP, Brasil), con Maestría en Diseño Digital y formación en Arquitectura. Es investigador reconocido por el Sistema Nacional de Investigadores de México (SNI) y profesor titular en la UABJO. Cuenta con más de una década de experiencia académica en diseño, medios digitales y ecología de medios. Ha liderado investigaciones internacionales y conferencias en Reino Unido, Argentina y Brasil. Ha sido becado por Santander, el Gobierno de México y nominado en festivales de cine digital. Fue seleccionado por su visión transdisciplinar, liderazgo académico y compromiso con la innovación en diseño y tecnología.',
                'specialization' => 'Doctor en Diseño de Producto y Maestría en Diseño Digital',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Ricardo Alexis',
                'last_name' => 'López Gallego',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Consultor en Finanzas para la Conservación, participó en la estructuración e implementación de estrategias de inversión y movilización de recursos para proyectos como Herencia Colombia, Manglares para el clima y la comunidad, Sirap Pacífico, Sirap Eje Cafetero, entre otros.
                        Soy especialista en finanzas para la conservación y el desarrollo sostenible, con más de 12 años de experiencia en estrategias de financiamiento para proyectos ambientales y de cambio climático. He participado en iniciativas de compensaciones por pérdida de biodiversidad, Pago por Servicios Ambientales -PSA, Bancos de Hábitat, proyectos bancables, REDD+, Soluciones Basadas en la Naturaleza, entre otras. También cuento con experiencia en análisis de política pública ambiental, taxonomías verdes, estudios de impacto ambiental, reportes de sostenibilidad, metodología de Marco Lógico, Teoría del Cambio y Metodología General Ajustada -MGA, así como en docencia, investigación y producción de textos',
                'specialization' => 'Finanzas para la conservación y el desarrollo sostenible',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Gerardo',
                'last_name' => 'Luna Gijón',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Profesor de tiempo completo en el Colegio de Diseño Gráfico de la Benemérita Universidad Autónoma de Puebla, especializado en diseño de información. Su trayectoria profesional incluye experiencia en diseño editorial y diseño de experiencia de usuario (UX), campos en los que ha desarrollado propuestas centradas en la claridad comunicativa y la funcionalidad visual.
                        Su línea de interés se enfoca en la intersección entre el diseño y la divulgación científica, explorando cómo el diseño contribuye a facilitar la comprensión de contenidos complejos. Este enfoque lo ha llevado a profundizar en la infografía como medio expresivo y didáctico, en el que destaca la narrativa visual como herramienta clave para gestionar la experiencia del conocimiento en las personas. Su trabajo busca integrar estética, estructura y contenido en propuestas que potencien el entendimiento y la apropiación del conocimiento por parte del público.',
                'specialization' => 'Especializado en diseño de información',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Miguelina',
                'last_name' => 'Ruiz Díaz',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Licenciada en Administración Hotelera, especialista en Marketing Turístico y amplia experiencia en Comercialización Hotelera y Relaciones Públicas.
                        Se ha desempeñado a lo largo de su carrera en diversas áreas del sector turismo, ocupando cargos gerenciales en mayoristas de turismo y tour operadores en la ciudad de Caracas, Venezuela donde por más de 10 años estuvo promoviendo Venezuela en eventos y ferias internacionales.
                        Desde 2022 se desempeña como directora de la OPT aportando su experiencia en el área para el fortalecimiento de las alianzas entre los principales actores del turismo, tanto en Colombia como en su pais, Republica Dominicana.',
                'specialization' => 'Especialista en Marketing Turístico',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Héctor Daniel',
                'last_name' => 'Martínez',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Lic en Turismo. Experto Internacional en Turismo Rural- Desarrollo Turístico Sustentable. Desarrollo Económico.
                        Planificación Estratégica Participativa  y Proyectos Turísticos.',
                'specialization' => 'Experto Internacional en Turismo Rural',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Alejandra',
                'last_name' => 'Izquierdo Cujar',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Aty Duneika (Madre de la Bondad) en lengua IKU. Líder étnica del modelo de desarrollo turístico de la Sierra Nevada de Santamarta bajo el esquema de “ VOLUNTURISMO.
                        Asesora en Asuntos Legislativos de la Comisión Sexta Primera Vicepresidencia, Cámara de Representantes, asuntos de enfoque en inclusión social, equidad territorial y defensa de los derechos de los pueblos indígenas. Coordinadora de Asuntos Políticos Institucionales ante Organismos Multilaterales, liderando el relacionamiento temático y técnico con instancias como la Organización de las Naciones Unidas (ONU) y la Organización de Estados Americanos (OEA), desde el despacho del Canciller de Colombia. Mujer indígena, miembro de la comunidad Arhuaca , Ingeniera Industrial, con estudios de maestría en Project Management, Gestión Pública y Gobierno, Alta Dirección Pública, Gerencia de Proyectos y Estudios Interdisciplinarios sobre
                        Desarrollo.',
                'specialization' => 'Maestría en Project Management, Gestión Pública y Gobierno',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Andrea Paola',
                'last_name' => 'Santanilla Narvaez',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Economista con sólida formación a nivel académico, incluyendo maestrías en economía y emprendimiento social. Posee amplia experiencia en funciones técnicas y directivas tanto en el sector público (en pensiones y contribuciones) como en el sector privado (AXA Colpatria). Actualmente lidera la Dirección de Inversión Extranjera y Servicios en Mincomercio, desempeñándose en un nivel directivo clave para la política de atracción de inversión y desarrollo de servicios económicos.',
                'specialization' => 'Maestrías en economía y emprendimiento social',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Luis',
                'last_name' => 'Aníbal Mora García',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Ingeniero Industrial de la Universidad Nacional de Colombia. Especialista en Mercadeo Internacional de la Universidad Eafit , Maestría de Dirección Logistica y Operaciones en la Escuela de Negocios ENAE Murcia, España, Certificado en Logística y Distribución del Logistics Institute of London, Inglaterra España.
                        Actual Docente Catedrático en las Maestrías de Logística de la escuela de negocios EAE de Madrid, España, Master de logística de la Universidad de Monterrey, México, Universidad de las Américas de Ecuador, Universidad Latina de ciudad de Panamá, Universidad de Medellín, Universidad tecnológica de Cartagena. Profesor invitado a la Maestría de Logística en Defensa y Seguridad, Univ. Rey Juan Carlos de Madrid, España, ExInstructor de logística del Latin American Logistics Center de Atlanta, EE.UU. Catedrático de los Posgrados de Logística de las universidades Sergio Arboleda, Universidad del Magdalena, Universidad Autónoma de Bucaramanga, Universidad Javeriana de Cali y Universidad Jorge Tadeo Lozano de Bogotá, Colombia.',
                'specialization' => 'Especialista en Mercadeo Internacional, Maestría en Dirección Logística y Operaciones',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Angela',
                'last_name' => 'Pantoja',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Profesional con más de 11 años de experiencia en el diseño e implementación de estrategias turísticas innovadoras y sostenibles, con énfasis en la creación de experiencias de turismo comunitario, conservación ambiental y desarrollo territorial. Experiencia en liderazgo de proyectos, formación y acompañamiento a comunidades locales y desarrollo de políticas públicas en turismo.
                        Es profesional de Turismo del Instituto Distrital de Turismo de Bogotá en la estructuración y ejecución de estrategias para el fortalecimiento de proyectos de turismo de naturaleza y enfoque comunitario en territorios de alta vulnerabilidad, contribuyendo al cumplimiento de las metas del sistema turístico de Bogotá. Ha brindando asistencia técnica a más de 36 organizaciones comunitarias en 7 localidades para la estructuración de experiencias turísticas auténticas. Ha liderado la estrategia de marca de turismo comunitario "Bogotá, destino de experiencias auténticas". Ha dirigido la estructuración e implementación de la estrategia de turismo rural "Bogotá, un destino rural", ganadora del primer lugar en los Premios a la Alta Gerencia Distrital 2024, en la categoría "Bogotá confía en su Bienestar"',
                'specialization' => null,
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Franklin',
                'last_name' => 'Eduardo López',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Publicista y Magíster en Dirección de Marketing Estratégico por la Universidad de Investigación y Desarrollo (UDI) de Bucaramanga, Colombia. Se desempeña como docente investigador en los campos de la Publicidad y el Marketing Digital, donde orienta procesos formativos y académicos enfocados en estrategias de comunicación persuasiva, posicionamiento de marca y análisis de audiencias en entornos digitales.
                        Su perfil combina la formación creativa del publicista con una visión estratégica del marketing, lo que le permite abordar proyectos desde una perspectiva integral, centrada en el valor de las marcas y su relación con el consumidor. Como investigador, su trabajo se orienta al estudio de las dinámicas del mercado digital, el comportamiento del consumidor y la innovación publicitaria en escenarios contemporáneos.',
                'specialization' => 'Magíster en Dirección de Marketing Estratégico',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Julio César',
                'last_name' => 'Acosta Prado',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Post – Doctor en Administración de la Universidad de Sao Paulo, Doctor en Dirección y Organización de Empresas de la Universidad Autónoma de Madrid; Licenciado en Ciencias Políticas y de la Administración. Actualmente, Profesor Visitante Extraordinario de la Pontificia Universidad católica de Perú, Investigador y consultor Internacional de Empresas. Autor de numerosos artículos científicos y capítulos de libros. Evaluador y Miembro de Comités científicos y editoriales de revistas científicas nacionales e internacionales. Sus líneas de investigación se centran en: Gestión del conocimiento, capital intelectual, capacidades dinámicas, aprendizaje organizacional, emprendimiento, gestión tecnológicas e innovación.',
                'specialization' => 'Post-Doctor en Administración, Doctor en Dirección y Organización de Empresas',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Manuel',
                'last_name' => 'Fernández-Villacañas Marín',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Sin info',
                'specialization' => null,
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Lucía Corali Nelly',
                'last_name' => 'Risco Mc Gregor',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Magíster en Administración y Negocios Internacionales por la Universidad Tecnológica del Perú, Diseñadora de Interiores y Licenciada en Educación Artística por la Universidad de Chimbote. Su experiencia profesional se ha desarrollado en el sector de acabados y diseño, desempeñándose como asesora en empresas del rubro y como consultora especializada en interiorismo para constructoras.
                        Actualmente se dedica al diseño de interiores de espacios comerciales, integrando criterios estéticos, funcionales y estratégicos en cada proyecto. Es investigadora en temáticas relacionadas con el color y su influencia en los entornos habitables, articulando teoría y práctica en sus procesos creativos. Además, ejerce como docente en la Carrera de Diseño Profesional de Interiores en la Universidad Peruana de Ciencias Aplicadas, donde aporta su visión interdisciplinar y experiencia aplicada en el diseño de espacios.',
                'specialization' => 'Magíster en Administración y Negocios Internacionales',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Karina',
                'last_name' => 'Vélez Gómez',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Cuenta con 15 años de experiencia en telecomunicaciones, especializado en comunicaciones externas, medios y gestión de crisis. Ha liderado estrategias de posicionamiento para Telefónica en Hispanoamérica en segmentos B2C, B2B, responsabilidad social (Fundación Telefónica), innovación (Wayra) y ciberseguridad (Telefónica Tech). Posee experiencia nacional e internacional en patrocinios deportivos como ciclismo, fútbol y eSports. Su enfoque combina tecnología, relaciones públicas y metodologías ágiles. Fue seleccionado por su capacidad para comunicar con impacto, liderar en entornos de alta exigencia y generar valor real para las comunidades.',
                'specialization' => null,
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Magreth',
                'last_name' => 'Gutiérrez Vargas',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Galardonada con el premio Las Disruptoras, iupana Davivienda reconocimiento que destaca a las mujeres más influyentes que están a cargo de proyectos de crecimiento innovadores e impactantes
                        Cucuteña, emprendedora actualmente soy CEO y fundadora de Aavance Solutions Fintech SAS , una empresa comprometida con la inclusión social y financiera, cuyo propósito principal es acompañar a migrantes, personas retornadas y emprendedores en su integración al sistema financiero colombiano.
                        Soy ingeniera financiera egresada de la Universidad Autónoma de Bucaramanga (UNAB), con una sólida trayectoria en los sectores bancario, automotriz y de comercio internacional. A lo largo de mi carrera he combinado una visión estratégica con habilidades de liderazgo, lo que me ha permitido desarrollar e impulsar proyectos de alto impacto en el ámbito financiero y empresarial.',
                'specialization' => 'Ingeniera financiera',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Asia',
                'last_name' => 'Pellegrini',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Asia Pellegrini (Italia) y Luna T. García (España) son las emprendedoras detrás de Nothink Shoes, una innovadora marca europea de calzado con tacones intercambiables. Asia, licenciada en Business Management, lidera el desarrollo estratégico, mientras que Luna, técnica en Administración y Finanzas, ha impulsado la expansión en mercados hispanohablantes. Juntas promueven una moda inteligente, versátil y pensada para transformar la experiencia femenina con el calzado de tacón.',
                'specialization' => 'Licenciada en Business Management',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Luna T.',
                'last_name' => 'García',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Fundadora de Nothink Shoes (España). Técnica en Administración y Finanzas. Especialista en expansión de marcas hispanohablantes.',
                'specialization' => 'Técnica en Administración y Finanzas',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Juan Carlos',
                'last_name' => 'Peña Castro',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Profesional en Finanzas y Relaciones Internacionales y Licenciado en Economía, MBA en Business & Marketing y especializado en Salesforce E-commerce B2C. Apasionado por la tecnología y los nuevos cambios de la industria que obligan a reinventarse día tras día. Ayuda a las organizaciones en los procesos de Transformación Digital creando estrategias de Customer Centric en Marketing, eCommerce, Ventas y Servicios, para mejorar la experiencia de los clientes (B2B o B2C).
                        Redefine el comercio electrónico como una herramienta futurista y busca mejorar la atención al cliente para fidelizarlos con políticas de Customer Service ágiles y adaptadas a todos los públicos  sectores económicos.
                        Viajero incansable, le gusta combinar sus dos pasiones para descubrir lugares y culturas inolvidables.',
                'specialization' => 'MBA en Business & Marketing',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Alejandro',
                'last_name' => 'Fajardo',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => ' Especialista en gestión de proyectos, ingeniero agrónomo. Conferencista en turismo (comunitario, innovación, desarrollo de proyectos y sostenibilidad) de la Ruta Exportadora de ProColombia entre el 2020 – 2024), Diseño de productos turísticos con enfoque diferencial étnico enfocado a trabajo con pueblos, indígenas, planificación territorial y sostenibilidad. Experiencia de trabajo en Etnoturismo, turismo comunitario, turismo indígena y de naturaleza. Conferencista en turismo comunitario Procesos de inclusión social y productiva con comunidades étnicas (indígenas y afro). Concertación efectiva con 1.241 comunidades indígenas y 741 comunidades afro en el país. Diseño y puesta en marcha de modelos de planificación y gestión basados en alianzas entre empresas y entes gubernamentales, para el desarrollo de estrategias de creación o impulso de productos turísticos especializados, para segmentos de mercado definidos, añadiendoles valores diferenciados de calidad y competitividad que aseguren la reactivación económica del sector y la rentabilidad.',
                'specialization' => 'Especialista en gestión de proyectos',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Angela María',
                'last_name' => 'Galindo Cañon',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Maestra en Textiles de la Universidad de los Andes y Máster en Alta Dirección (Italia). Profesional de Gestión en Artesanías de Colombia, donde coordina el programa Territorio Moda y Joyería. Con amplia experiencia en asesoría a comunidades artesanales y desarrollo de producto, se especializa en innovación textil, técnicas ancestrales y fortalecimiento del sector artesanal a través de metodologías creativas y formativas.',
                'specialization' => 'Maestra en Textiles y Máster en Alta Dirección',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Claudia Marcela',
                'last_name' => 'Sanz',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Doctora en diseño de la Universidad Estadual Paulista. Directora del Programa de Diseño de Vestuario de la Universidad de San Buenaventura, Investigadora asociada de Minciencias en temas de innovación, tendencias y pronósticos de moda, medición del impacto del diseño y fortalecimiento empresarial.
                        Hace parte de la junta directiva de la Red Académica de Diseño, Consultora asociada de ACICAM, Asociación Colombiana de Industriales del calzado, el cuero y sus manufacturas, donde coordina el área de moda, desarrolla estudios sobre la capacidad del diseño del sector en Colombia y realiza talleres de formación para los empresarios asociados.
                        Autora de los libros Ciclos de la Moda, Estudio de la implementación del diseño en empresas del sector textil, cuero, confección, diseño y moda en la ciudad de Santiago de Cali, cuenta con 6 capítulos publicados sobre la innovación en el Valle del Cauca así como de artículos en revistas académicas.',
                'specialization' => 'Doctora en diseño',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Carlos Enrique',
                'last_name' => 'Fernández García',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Magíster en Educación y Comunicador experto en tecnologías emergentes y realidad aumentada aplicadas al periodismo, comunicación organizacional y diseño profesional. Cursó estudios en Inmmersive Journalism: Virtual Reality & 360 video en Knight Center to Journalism in the Americas. Se desempeña actualmente como encargado de la Oficina de Comunicación e Imagen Institucional de la Facultad de Letras de la Universidad Nacional Mayor de San Marcos, docente en la carrera de Comunicación Audiovisual y Medios Digitales de la Universidad Privada del Norte y en la Facultad de Periodismo de la Universidad Jaime Bausate y Meza.',
                'specialization' => 'Magíster en Educación',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Amalia',
                'last_name' => 'Aguilar Castillo',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Profesional comprometida con la educación superior, con más de tres años de experiencia como Directora de la Facultad de Comercio Internacional y Aduanas. Economista de formación, actualmente cursando el Doctorado en Educación, con un firme compromiso hacia la mejora continua y la innovación académica.
                        Directora de la Facultad de Comercio Internacional y Aduanas de la Universidad Xochicalco, Campus Tijuana, Docente de nivel superior, lidera la gestión académica y administrativa de la facultad, asegurando el cumplimiento de los estándares de calidad educativa, coordina la actualización curricular y procesos de acreditación (CONACI, FIMPES), Impulsa la vinculación con el sector empresarial para fortalecer prácticas profesionales y oportunidades de internacionalización, supervisa la organización de eventos académicos, capacitación docente y proyectos de investigación aplicada y Gestiona la operación académica en plataformas digitales y sistemas de gestión educativa.',
                'specialization' => 'Doctorado en Educación',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Diego',
                'last_name' => 'Santos González',
                'gmail' => null,
                'document_type_id' => null,
                'document_number' => null,
                'phone' => null,
                'bio' => 'Diego Santos González (Pontevedra, 1984), doctor en Sociología del Turismo por la Universidad Rey Juan Carlos (2016), ha desarrollado un perfil académico y profesional profundamente vinculado al turismo, el marketing y el comportamiento del consumidor. Su tesis doctoral, El mundo sobre las olas: Perspectiva de desarrollo turístico a través del surfing, explora las intersecciones entre turismo, deporte y naturaleza, abriendo una línea de investigación pionera sobre el surf como motor de desarrollo turístico sostenible y su impacto en las comunidades receptoras.
                        Actualmente es Director de los programas de máster en Turismo de EAE Business School y profesor en UNIE Universidad. Su trayectoria combina investigación académica, docencia universitaria e innovación educativa, con un firme compromiso por la transferencia social del conocimiento.',
                'specialization' => 'Doctor en Sociología del Turismo',
                'photo_url' => null,
                'linkedin_url' => null,
                'facebook_url' => null,
                'instagram_url' => null,
                'tiktok_url' => null,
                'youtube_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ];

        foreach ($speakers as $speaker) {
            Speaker::create($speaker);
        }
    }
}